apiVersion: v1
kind: Service
metadata:
  name: xerocodee-web-loadbalancer
spec:
  type: NodePort
  selector:
    app: xerocodee-web
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31000