name: Build Step 

on:
  push: 
    branches: ['master']

jobs : 
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci 
      - run: npm run build --if-present

  test-stage:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Running Tests
        uses: actions/checkout@v3
      - run: echo "XeroCodee CI"

  build-and-push-docker-iamge:
    name: Build Docekr iamge and push to repository
    runs-on: ubuntu-latest
    needs: ['build', 'test-stage']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Step up Docker Build
        id: build
        uses: docker/steup-build-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with: 
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.G_TOKEN }}

      - name: Build image and push to Docker Hub adn Github container registry
        uses: docker/build-push-actions@v2
        with: 

          context: ./
          tags: /
            xerocodee/xerocodee-web:${{ github.sha }}
            ghcr.io/xerocdee/xerocodee-web:${{ github.sha }}

          push: ${{ github.ref == 'refs/heads/master' }}

      - name: Image digest
        run: exhp ${{ steps.docker_build.outputs.digest }}
  
  update-mainfest-stage:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    steps:
      - uses: actions/checkout@v3
        with:
          repository: xerocodee/xerocodee.github.io
          ref: 'master'
          token: ${{ secrets.G_TOKEN }}

      - name: setup git config
        run: /
          git config --global user.email "aryasoni98@gmail.com"
          git config --global user.name "aryasoni98"
          echo ${{ github.sha }}
          sed -i "s#${{ github.actor }}.*#${{ github.actor }}/xerocodee-web:${{ github.sha }}#g" deployment.yaml
          git add - A
          git commit -am "Update image for - ${{ github.sha }}"
      - run: echo ${{ github }}
      - run: git push origin master
